# Generated by Django 3.0.7 on 2022-08-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=255)),
                ('status', models.CharField(choices=[('1', 'Available'), ('2', 'Not Available')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.CharField(choices=[('1', 'Available'), ('2', 'Not Available')], default=1, max_length=10),
        ),
    ]
